version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: employee_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    container_name: node_api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://admin:password123@db:5432/employee_db"

  frontend:
    container_name: react_ui
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

volumes:
  postgres_data: